# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a43b78caff6c4a6bf224c68b0c6b5cb4594039ce4cc54ea5948ada8f0d6130b54dd37037c14b52930a0c4f6562da64baefaa5f0079c9acd57cfcd6d9bcdbb92

test:
  secret_key_base: 674634ba9993a900eca282576ce944803579507b12c6b3a341d12996c209111097f8b032fdadcf95158924bdcc1357868cb4c69f7b11e3f0133e5b7144c44e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  AWS_REGION: <%= ENV["AWS_REGION"] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  S3_BUCKET_NAME: <%= ENV["S3_BUCKET_NAME"] %>
